import type { PlatformE2eConfig } from "task-e2e";

export const wrikeE2eConfig: PlatformE2eConfig = {
  platformName: "wrike",
  platformDisplayName: "Wrike",
  oauthMessagePlatform: "wrike",
  sessionCookieName: "wrike_session_token",
  taskManagerPath: "/task-manager-extension",
  connectionTitle: "Connect to Wrike",
  hasPlatformLogo: true,
  connectButtonTestId: "connect-wrike-account",
  connectionStatusApiPath: "/api/auth/wrike/status",
  disconnectApiPath: "/api/auth/wrike/disconnect",
  setupApiPath: "/api/setup",
  hasSites: false,
  hasSetupWizard: true,
  hasIssueTypes: false,
  hasPriorities: true,
  hasAssignees: true,
  hasDueDate: true,
  hasParentIssue: true,
  hasComments: true,
  hasCommentReplies: true,
  hasSubtasks: true,
  hasStatusTransitions: true,
  hasAttachments: true,
  hasExternalResourceMappings: true,
  setupScopeLevelIds: ["folder"],
  taskListScopeLevelId: "folder",
  richTextFormat: "plain",
};
