import type { GeneratorCallback } from "@nx/devkit";
import { formatFiles, joinPathFragments, names, Tree } from "@nx/devkit";
import { libraryGenerator } from "@nx/js/src/generators/library/library";
import type { LibraryGeneratorSchema } from "@nx/js/src/generators/library/schema";
import { applicationGenerator } from "@nx/next/src/generators/application/application";
import type { Schema as NextAppSchema } from "@nx/next/src/generators/application/schema";

import { BUILTIN_CAPABILITY_IDS, BUILTIN_UI_SWITCH_IDS } from "./constants";
import { getGeneratedCapabilityFlags } from "./default-capability-matrix";
import {
  CAPABILITY_REGISTRY_EXTENSIONS_FILE,
  PLATFORM_UI_SCHEMA_EXTENSIONS_FILE,
  TASK_PLATFORM_REGISTRY_EXTENSIONS_FILE,
} from "./registry-paths";
import { assertSafePlatformGeneration, assertWritePathAllowed } from "./safety";
import type { PlatformAppGeneratorSchema, PlatformKind } from "./schema";
import { assertValidPlatformSchema } from "./validate-platform-schema";

function safeWrite(tree: Tree, path: string, content: string): void {
  assertWritePathAllowed(path.replace(/\\/g, "/"));
  tree.write(path, content);
}

function appendBeforeMarker(content: string, marker: string, insertion: string): string {
  const trimmed = insertion.trim();
  if (trimmed && content.includes(trimmed)) {
    return content;
  }
  const idx = content.indexOf(marker);
  if (idx === -1) {
    throw new Error(`Marker not found: ${marker}`);
  }
  return `${content.slice(0, idx)}${insertion}\n${content.slice(idx)}`;
}

function stubProviderSource(args: {
  className: string;
  fileName: string;
  platformId: string;
}): string {
  return `import type {
  GetTasksOptions,
  PlatformProject,
  PlatformTask,
  TaskPlatformProvider,
} from "@sai-mp-jira-task-view/platform";

import type { JiraBffTransportOptions } from "@sai-mp-jira-task-view/jira-providers";

/**
 * Generated stub for "${args.platformId}" (Phase 6.2 platform-app).
 * Replace with real BFF integration; keep {@link TaskPlatformProvider} contract.
 */
export class ${args.className}TaskPlatformProvider implements TaskPlatformProvider {
  constructor(_options?: JiraBffTransportOptions) {}

  async getProjects(): Promise<PlatformProject[]> {
    return [];
  }

  async getTasks(_projectKey: string, _options?: GetTasksOptions): Promise<PlatformTask[]> {
    return [];
  }
}
`;
}

function capabilityBlockSource(className: string, platformId: string, kind: PlatformKind): string {
  const flags = getGeneratedCapabilityFlags(kind);
  const lines = Object.entries(flags)
    .map(([k, v]) => `      "${k}": ${v},`)
    .join("\n");
  return `import type { PlatformCapabilities } from "../capability-types";

export const ${className}Capabilities: PlatformCapabilities = {
  platform: "${platformId}",
  version: "1.0",
  capabilities: {
${lines}
  },
};
`;
}

function uiSchemaEntry(platformId: string): string {
  return `  ${platformId}: {
    type: "container",
    children: [
      { type: "feature", key: "tasks.status" },
      { type: "feature", key: "tasks.assign" },
    ],
  },`;
}

function platformConfigSource(platformId: string): string {
  return `export const PLATFORM_CONFIG = {
  platform: "${platformId}",
  capabilities: "auto" as const,
} as const;
`;
}

function envTemplateSource(platformId: string): string {
  const p = platformId.toUpperCase().replace(/[^A-Z0-9]/g, "_");
  return `# ${platformId} — generated by platform-generator (Phase 6.2)
# OAuth (example keys)
${p}_CLIENT_ID=
${p}_CLIENT_SECRET=

# API base URL
${p}_API_BASE_URL=

# Supabase (optional)
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
`;
}

function rootEntryPageSource(platformId: string): string {
  return `'use client';

import { DynamicUI } from "@sai-mp-jira-task-view/capabilities";

export default function Index() {
  return (
    <div style={{ padding: 24, fontFamily: "system-ui" }}>
      <h1>${platformId} app shell</h1>
      <p>Capability-driven placeholder (Phase 6.2).</p>
      <DynamicUI platform="${platformId}" />
    </div>
  );
}
`;
}

function nextConfigForPlatform(): string {
  return `//@ts-check

const { composePlugins, withNx } = require("@nx/next");

/**
 * @type {import('@nx/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  nx: {},
  transpilePackages: [
    "@sai-mp-jira-task-view/capabilities",
    "@sai-mp-jira-task-view/platform",
  ],
};

const plugins = [withNx];

module.exports = composePlugins(...plugins)(nextConfig);
`;
}

/**
 * Phase 6.4 — orchestration entry (steps map to doc: app → provider → capabilities → registry → env).
 */
export async function platformAppGenerator(
  tree: Tree,
  options: PlatformAppGeneratorSchema,
): Promise<GeneratorCallback> {
  const resolved = assertValidPlatformSchema(options);
  const { id, type: platformKind } = resolved;

  assertSafePlatformGeneration(id);

  const nameVariants = names(id);
  const pascal = nameVariants.className;
  const callbacks: GeneratorCallback[] = [];

  const appRoot = joinPathFragments("apps", `${id}-app`);
  const appProjectJson = joinPathFragments(appRoot, "project.json");
  const appExisted = tree.exists(appProjectJson);

  if (!appExisted) {
    const nextOpts: NextAppSchema = {
      directory: appRoot,
      name: `${id}-app`,
      style: "css",
      linter: "eslint",
      e2eTestRunner: "none",
      unitTestRunner: "none",
      appDir: true,
      src: true,
      skipFormat: true,
      useProjectJson: true,
      tags: `type:app,scope:${id}`,
      skipPackageJson: true,
    };
    const cb = await applicationGenerator(tree, nextOpts);
    if (cb) {
      callbacks.push(cb);
    }
    safeWrite(tree, joinPathFragments(appRoot, "next.config.js"), nextConfigForPlatform());
    safeWrite(tree, joinPathFragments(appRoot, "src", "app", "page.tsx"), rootEntryPageSource(id));
  }

  const platformConfigPath = joinPathFragments(appRoot, "src", "config", "platform.config.ts");
  if (!tree.exists(platformConfigPath)) {
    safeWrite(tree, platformConfigPath, platformConfigSource(id));
  }

  const envPath = joinPathFragments(appRoot, `.env.${id}.template`);
  if (!tree.exists(envPath)) {
    safeWrite(tree, envPath, envTemplateSource(id));
  }

  const providerLibJson = joinPathFragments("libs", "providers", id, "project.json");
  if (!tree.exists(providerLibJson)) {
    const libOpts: LibraryGeneratorSchema = {
      directory: joinPathFragments("libs", "providers", id),
      name: `${id}-providers`,
      importPath: `@sai-mp-jira-task-view/${id}-providers`,
      tags: "scope:providers,type:generated-platform",
      unitTestRunner: "none",
      linter: "none",
      skipFormat: true,
      minimal: true,
      bundler: "tsc",
      compiler: "tsc",
      useProjectJson: true,
      skipPackageJson: true,
      strict: true,
    };
    const cb = await libraryGenerator(tree, libOpts);
    if (cb) {
      callbacks.push(cb);
    }

    const junkLibFile = joinPathFragments(
      "libs",
      "providers",
      id,
      "src",
      "lib",
      `${id}-providers.ts`,
    );
    if (tree.exists(junkLibFile)) {
      tree.delete(junkLibFile);
    }

    const providerPkgPath = joinPathFragments("libs", "providers", id, "package.json");
    if (tree.exists(providerPkgPath)) {
      const pkg = JSON.parse(tree.read(providerPkgPath, "utf-8") as string) as {
        type?: string;
        [k: string]: unknown;
      };
      delete pkg.type;
      safeWrite(tree, providerPkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
    }

    const providerFile = joinPathFragments(
      "libs",
      "providers",
      id,
      "src",
      "lib",
      `${nameVariants.fileName}-task-platform-provider.ts`,
    );
    safeWrite(
      tree,
      providerFile,
      stubProviderSource({
        className: pascal,
        fileName: nameVariants.fileName,
        platformId: id,
      }),
    );

    const indexPath = joinPathFragments("libs", "providers", id, "src", "index.ts");
    safeWrite(
      tree,
      indexPath,
      `export { ${pascal}TaskPlatformProvider } from "./lib/${nameVariants.fileName}-task-platform-provider";\n`,
    );
  }

  if (!BUILTIN_CAPABILITY_IDS.has(id)) {
    const capFile = joinPathFragments(
      "libs",
      "capabilities",
      "src",
      "lib",
      "platforms",
      `${id}.capabilities.ts`,
    );
    safeWrite(tree, capFile, capabilityBlockSource(pascal, id, platformKind));

    let capExt = tree.read(CAPABILITY_REGISTRY_EXTENSIONS_FILE, "utf-8")!;
    capExt = appendBeforeMarker(
      capExt,
      "// @nx-capability-registry-extensions:imports-end",
      `import { ${pascal}Capabilities } from "./platforms/${id}.capabilities";`,
    );
    capExt = appendBeforeMarker(
      capExt,
      "// @nx-capability-registry-extensions:entries-end",
      `  ${id}: ${pascal}Capabilities,`,
    );
    safeWrite(tree, CAPABILITY_REGISTRY_EXTENSIONS_FILE, capExt);
  }

  if (!BUILTIN_UI_SWITCH_IDS.has(id)) {
    let uiExt = tree.read(PLATFORM_UI_SCHEMA_EXTENSIONS_FILE, "utf-8")!;
    if (!uiExt.includes(`${id}: {`)) {
      uiExt = appendBeforeMarker(
        uiExt,
        "// @nx-platform-ui-schema-extensions:entries-end",
        uiSchemaEntry(id),
      );
      safeWrite(tree, PLATFORM_UI_SCHEMA_EXTENSIONS_FILE, uiExt);
    }
  }

  let provExt = tree.read(TASK_PLATFORM_REGISTRY_EXTENSIONS_FILE, "utf-8")!;
  if (!provExt.includes(`  ${id}: ${pascal}TaskPlatformProvider`)) {
    provExt = appendBeforeMarker(
      provExt,
      "// @nx-platform-registry-extensions:imports-end",
      `import { ${pascal}TaskPlatformProvider } from "../../../${id}/src/lib/${nameVariants.fileName}-task-platform-provider";`,
    );
    provExt = appendBeforeMarker(
      provExt,
      "// @nx-platform-registry-extensions:entries-end",
      `  ${id}: ${pascal}TaskPlatformProvider,`,
    );
    safeWrite(tree, TASK_PLATFORM_REGISTRY_EXTENSIONS_FILE, provExt);
  }

  await formatFiles(tree);

  return async () => {
    for (const cb of callbacks) {
      if (cb) {
        await cb();
      }
    }
  };
}

export default platformAppGenerator;
