-- Scaffold Wrike tables.
-- Generated by: npx nx g @mp/generators:platform-app wrike

-- Wrike core connection + session tables.

create table if not exists public.wrike_connections (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  -- Data-centre host from OAuth token response (e.g. https://app-us2.example.com).
  -- Empty string for legacy connections; repaired on next token refresh.
  wrike_site text not null default '',
  wrike_project text not null default '',
  wrike_account_id text,
  access_token_encrypted text not null,
  refresh_token_encrypted text,
  expiry timestamptz not null,
  status text not null default 'active'
    check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create index if not exists idx_wrike_connections_user_id
  on public.wrike_connections (user_id, status);

create table if not exists public.wrike_sessions (
  id uuid primary key default gen_random_uuid(),
  session_token text unique not null,
  wrike_account_id text not null,
  created_at timestamp default now(),
  expires_at timestamp not null
);

create index if not exists idx_wrike_sessions_token
  on public.wrike_sessions (session_token);

-- Wrike setup wizard state (folder selection + completion gate).
create table if not exists public.wrike_user_setup (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  wrike_connection_id uuid not null references public.wrike_connections (id) on delete cascade,
  wrike_site_id text not null,
  wrike_site_url text not null,
  wrike_site_name text,
  default_project_id text not null,
  default_project_key text not null,
  default_project_name text,
  scope_selections jsonb,
  task_list_scope_level_id text default 'folder',
  -- NULL = wizard in progress; non-NULL = completed and Task View is accessible.
  setup_completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create index if not exists idx_wrike_user_setup_user_id
  on public.wrike_user_setup (user_id);

create index if not exists idx_wrike_user_setup_connection_id
  on public.wrike_user_setup (wrike_connection_id);

comment on column public.wrike_user_setup.scope_selections is
  'JSON map of scope level id → { id, key, name } selection.';

comment on column public.wrike_user_setup.task_list_scope_level_id is
  'Leaf scope level whose selection gates the task list (wrike: folder).';

-- Per-Sitecore-site Wrike scope overrides (context-aware task list).
create table if not exists public.wrike_site_project_mappings (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  wrike_connection_id uuid not null references public.wrike_connections (id) on delete cascade,
  sai_site_id text not null,
  sai_site_name text,
  wrike_site_id text,
  wrike_site_url text,
  wrike_site_name text,
  wrike_project_id text not null,
  wrike_project_key text not null,
  wrike_project_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_wrike_site_project_mappings_user_id
  on public.wrike_site_project_mappings (user_id);

create index if not exists idx_wrike_site_project_mappings_connection_id
  on public.wrike_site_project_mappings (wrike_connection_id);

create unique index if not exists uq_wrike_site_project_mappings_user_sai_site
  on public.wrike_site_project_mappings (user_id, sai_site_id);

comment on table public.wrike_site_project_mappings is
  'Maps Sitecore websites to Wrike folders for context-aware task management.';
